# Generated by Django 2.0.2 on 2018-02-25 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=300)),
                ('text_recipe', models.TextField()),
                ('img_main', models.ImageField(upload_to='')),
                ('img1', models.ImageField(blank=True, upload_to='photo/')),
                ('img2', models.ImageField(blank=True, upload_to='photo/')),
                ('img3', models.ImageField(blank=True, upload_to='photo/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
