# Generated by Django 2.0.2 on 2018-03-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='img_main',
            field=models.ImageField(blank=True, upload_to='photo/'),
        ),
    ]
